### ISSUE TITLE
Avaliação interna do grupo

### ISSUE THREAD

**Issue by joaozarate** [ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-conecta#109]
https://docs.google.com/document/d/1CDtkbVEBme7WebA4qcQOaWuWjwp6MqtyETNxD8oScQg/edit?usp=sharing

**Comment by gabrielrnascimento** [comment]
Doc para nova etapa

https://docs.google.com/document/d/12C4hGBBTwBOd9XCKkIkOsv-T-g-RyXZhqwyxVXmufgY/edit#heading=h.fcha9ct156vz
