### ISSUE TITLE
[RF-09] - Ajustes de layout da landing page

### ISSUE THREAD

**Issue by joaozarate** [ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-conecta#126]
- [ ]  Remover javascript e utilizar css

**Comment by AliceAbreu** [comment]
- [ ] Aumentar e centralizar o tamanho do logo na versão mobile;
- [ ] Na tela menu, formatar fonte, cor, espaçamento e ordem dos links "sobre o voluntariado", "como começar?", "por que ser voluntário?", "histórias de sucesso" e "perguntas frequentes";
- [ ] Na tela menu aumentar e centralizar e o logo;
- [ ] Sombreado quando o menu estiver aberto.
