### ISSUE TITLE
[Story] - Definições arquiteturais

### ISSUE THREAD

**Issue by joaozarate** [ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-conecta#215]
Definiremos as questões arquiteturais da aplicação como 

- [ ] componentes reutilizaveis
- [ ] funções reutilizaveis
- [ ] comunicação entre telas
- [x] objetos de domínio
    - [x] `Organization` (classe para ONG) Em desenvolvimento -> @gabrielrnascimento 
    - [x] `Task` (classe para Demanda) -> @gabrielrnascimento 
    - [x] `Review` (classe para Depoimento) -> @gabrielrnascimento 
    - [x] `Candidate` (classe para Candidato) -> @gabrielrnascimento 
    - [x] `Session` (classe para Sessão de autenticação) -> @joaozarate 
- [ ] estrutura de diretórios
- [x] comunicação com o json server -> @gabrielrnascimento 
- [x] email (aceitar e recusar condidatura, depoimento, notificação de candidatura para a ONG) -> @gabrielrnascimento 
- [x] routes

**Comment by joaozarate** [comment]
https://www.jsonserver.io/#example-fetch

**Comment by gabrielrnascimento** [comment]
Fiz o deploy de um json-server na vercel pq essa solução que colocamos acima tinha um limite de rotas e requests diários.

Link do json-server na vercel
https://json-server-vercel-eta-beige.vercel.app/

**Comment by gabrielrnascimento** [comment]
#216 Aberto relacinado à comunicação HTTP e criação dos Objetos de domínio

**Comment by gabrielrnascimento** [comment]
#218 Aberto relacionado à envio de email

**Comment by joaozarate** [comment]
https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-conecta/pull/279 definições de sessão
