### ISSUE TITLE
CT27 - Interface simples

### ISSUE THREAD

**Issue by arondightt** [ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-conecta#261]
RNF-002 A aplicação deve apresentar um layout simples e de fácil utilização.

**Comment by gabrielrnascimento** [comment]
- Mostrar tratamento nos formulários (CNPJ com máscara, por exemplo)
- Não precisa ser um vídeo, pode ser um documento fazendo um pararelo com as [heurísticas de nielsen](https://brasil.uxdesign.cc/10-heur%C3%ADsticas-de-nielsen-para-o-design-de-interface-58d782821840)
