### ISSUE TITLE
Institucional - Landing Page

### ISSUE THREAD

**Issue by joaozarate** [ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-conecta#61]
RF-009 - Deve existir uma página inicial (landing page) informativa que apresenta o propósito da plataforma e incentiva tanto as ONGs quanto os voluntários a utilizar a aplicação.

**Comment by gabrielrnascimento** [comment]
- Página com mensagem descritiva sobre o site
- Links para as páginas institucionais

**Comment by AliceAbreu** [comment]
Essa parte do link para as páginas institucionais ficará em "menu de acesso".
