### ISSUE TITLE
Institucional - Como Começar

### ISSUE THREAD

**Issue by joaozarate** [ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-conecta#62]
RF-008 - A aplicação deve apresentar a página “Como Começar” que orienta os visitantes sobre os passos necessários para se tornarem voluntários registrados na aplicação.

**Comment by gabrielrnascimento** [comment]
# Material para revisão

![Image](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-conecta/assets/59718237/e1b13d88-8b32-44e5-9ae3-9608874edbd9)

**Comment by gabrielrnascimento** [comment]
## Pontos de debate

- O que acham de colocarmos a imagem dessa forma ao invés de preencher toda a tela? Acho que fica bom das duas formas, apenas dando uma idéia.
- Essa página estaria ligando todas a páginas da aplicação que estão relacionadas com as ações de demanda/voluntariado (conferir user flow), as partes que estão <ins>**dessa forma**</ins> seriam links que levariam a essas páginas.
