### ISSUE TITLE
Página da ONG

### ISSUE THREAD

**Issue by joaozarate** [ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-conecta#68]
RF-021 - Os depoimentos dos voluntários devem ser disponibilizados no perfil da ONG que fez a solicitação.

**Comment by gabrielrnascimento** [comment]
Acho que esse item deve ser a página da ONG em si, que apresenta:
- Sobre (detalhes da ONG)
- Oportunidades (que foram abertas)
- Depoimentos

**Comment by gabrielrnascimento** [comment]
# Material para revisão

👍🏻 para aprovar


![Image](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-conecta/assets/59718237/9df259eb-258b-4958-be2f-5fadf8e6f038)

**Comment by AliceAbreu** [comment]
Gabriel, posso só formatar a parte dos cards para deixar igual na parte de demandas?

**Comment by gabrielrnascimento** [comment]
Não sei se entendi muito bem, seria deixar igual a parte da página de listagem?

Eu achei que os cards não fossem ficar exatamente iguais pela questão da foto de perfil da ONG, mas pode sim, sem problemas :)
